# Generated by Django 4.2.2 on 2024-01-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('alt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetalEarth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True)),
                ('main_pic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_sculp', to='myWebsite.picture')),
                ('picture', models.ManyToManyField(blank=True, to='myWebsite.picture')),
            ],
        ),
    ]
